name: Build & Deploy - Staging
on:
  push:
    - staging
    - main
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    #      permissions:
    #        contents: read
    #        security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDL 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven

      - name: Unit test
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: mvn -B package --file pom.xml

